-- !Ups

CREATE TYPE "STATUS" AS ENUM ('TO DO', 'IN PROGRESS', 'DONE');

CREATE TABLE "TASKS" (
  "ID" UUID PRIMARY KEY,
  "NAME" VARCHAR(250) NOT NULL,
  "STATUS" "STATUS" DEFAULT ('TO DO'),
  "DESCRIPTION" VARCHAR(1000)
);

-- !Downs

DROP TABLE "TASKS";
DROP TYPE "STATUS";